### PR TITLE
Store safe address

### PR DESCRIPTION
**Pull request by jmoreira-valory**
Store safe address

RE: https://github.com/valory-xyz/trader-quickstart/issues/16

### CODE REVIEW

**Comment by jmoreira-valory** [comment]
@Adamantios:
`Why store this information? It is not used by the script, it is printed for the user to copy it if they want, plus it can be seen in the docker compose file.`

Because it's easier to retrieve for a user that don't want to run the scripts and only inspect either Gnosisscan or using the .trades.py. Otherwise it gas to dig into more complex YAML files or go to the online registry using the service ID to find out their service Safe address.

**Review by dvilelaf — APPROVED** [review]

**Comment by Adamantios** [comment]
> @Adamantios:
> 
> > Why store this information? It is not used by the script, it is printed for the user to copy it if they want, plus it can be seen in the docker compose file.
> 
> Because it's easier to retrieve for a user that just wants to inspect either Gnosisscan or using the .trades.py without running the agent. Otherwise it has to dig into more complex YAML files or go to the online registry using the service ID to find out their service Safe address.

The point is that this is not what the `.trader_runner` is meant for and it should ultimately encode all the information in there as they are sensitive.

**Comment by jmoreira-valory** [comment]
I don't see why storing that information in the .store is a problem.
Additionally, it could be used, as a suggested improvement, to run the ".trades.py" script without arguments, and it will read by default the safe address stored in there.

**Comment by Adamantios** [comment]
> Additionally, it could be used, as a suggested improvement, to run the ".trades.py" script without arguments

This changes the whole conversation.

**Review by Adamantios — APPROVED** [review]

**Pull request merged**
